// docs/src/examples/date-picker/ColumnsType.vue
<script setup lang="ts">
import { DatePicker } from '@component-hook/picker/vue';
import { ref } from 'vue';

const currentDate = ref<number[]>([2030, 8]);
</script>

<template>
  <date-picker
    v-model="currentDate"
    class="max-w-125 rounded-lg"
    :columns-type="['year', 'month']"
  />

  <p class="mt-6 font-mono text-sm">Selected date: {{ currentDate.join(' / ') || 'not selected yet' }}</p>
</template>

// playground/react/src/pages/date-picker/components/columns-type.tsx
import { DatePicker, type DatePickerColumnType } from '@component-hook/picker/react';
import { useState } from 'react';

const columnsType: DatePickerColumnType[] = ['year', 'month'];

export function ColumnsTypePicker() {
  const [pickerValues, setPickerValues] = useState<number[]>([2030, 8]);

  return (
    <div style={{ maxWidth: '500px' }}>
      <DatePicker
        values={pickerValues}
        columnsType={columnsType}
        onChange={setPickerValues}
      />

      <p>Selected date: {pickerValues.join(' / ') || 'not selected yet'}</p>
    </div>
  );
}
