// packages/picker/src/vue/components/PickerColumn.vue
<script setup lang="ts" generic="T">
import { toRef } from 'vue';
import { OPTION_HEIGHT, OPTION_ROTATE_FACTOR } from '../../shared/constants';
import { useScrollSnap } from '../hooks/use-scroll-snap';
import type { PickerColumn, PickerFields } from '../../shared/types';

export interface Props<T> {
  column: PickerColumn<T>;
  fields: Required<PickerFields>;
  selectedIndex?: number;
}

interface Emits {
  change: [index: number];
}

const props = withDefaults(defineProps<Props<T>>(), {
  selectedIndex: 0,
});
const emits = defineEmits<Emits>();

const { offsetY, transitionDuration, onPointerDown, onPointerMove, onPointerUp, stopInertialSliding, scrollToIndex } =
  useScrollSnap({
    column: toRef(props, 'column'),
    onChange: onSelectedChange,
  });

function onSelectedChange(index: number) {
  if (index === props.selectedIndex) return;

  emits('change', index);
}

function scrollToSelected(index = props.selectedIndex, behavior?: ScrollBehavior) {
  scrollToIndex(index, behavior);
}

function onClick(index: number) {
  if (index === props.selectedIndex) return;

  scrollToSelected(index, 'smooth');
}

defineExpose({ scrollToSelected });
</script>

<template>
  <div
    class="chook-picker-column"
    aria-label="Picker column"
    @touchstart.passive="onPointerDown"
    @touchmove.prevent="onPointerMove"
    @touchend.passive="onPointerUp"
    @touchcancel="onPointerUp"
    @mousedown.passive="onPointerDown"
    @mousemove.passive="onPointerMove"
    @mouseup.passive="onPointerUp"
    @mouseleave.passive="onPointerUp"
  >
    <ul
      :style="{
        overflowY: 'hidden',
        transform: `translate3d(0, ${offsetY}px, 0)`,
        transitionDuration: `${transitionDuration}ms`,
        transitionProperty: transitionDuration ? 'all' : 'none',
      }"
      @transitionend="stopInertialSliding"
    >
      <li
        v-for="(option, index) in column"
        :key="option?.[fields.value]"
        class="chook-picker-column-item"
        role="button"
        tabindex="0"
        @click="onClick(index)"
      >
        <p
          class="chook-picker-column-label"
          :style="{
            transform: `rotate3d(1, 0, 0, ${(index * OPTION_HEIGHT + offsetY) * OPTION_ROTATE_FACTOR}deg)`,
          }"
        >
          {{ option?.[fields.label] }}
        </p>
      </li>
    </ul>
  </div>
</template>

// packages/picker/src/react/components/picker-column.tsx
import { forwardRef, useImperativeHandle } from 'react';
import { OPTION_HEIGHT, OPTION_ROTATE_FACTOR } from '../../shared/constants';
import { useScrollSnap } from '../hooks/use-scroll-snap';
import type { PickerColumn, PickerFields } from '../../shared/types';

type Props = {
  column: PickerColumn;
  fields: Required<PickerFields>;
  selectedIndex?: number;
  onChange: (index: number) => void;
};

export type ColumnRef = {
  scrollToSelected: (index?: number, behavior?: ScrollBehavior) => void;
};

export const Column = forwardRef<ColumnRef, Props>(({ column, fields, selectedIndex = 0, onChange }, ref) => {
  const { offsetY, transitionDuration, onPointerDown, onPointerMove, onPointerUp, stopInertialSliding, scrollToIndex } =
    useScrollSnap({
      column,
      onChange: handleSelectedChange,
    });

  useImperativeHandle(ref, () => ({
    scrollToSelected,
  }));

  function handleSelectedChange(index: number) {
    if (index === selectedIndex) return;

    onChange(index);
  }

  function scrollToSelected(index = selectedIndex, behavior?: ScrollBehavior) {
    scrollToIndex(index, behavior);
  }

  function onClick(index: number) {
    if (index === selectedIndex) return;
    scrollToSelected(index, 'smooth');
  }

  return (
    <div
      role="presentation"
      className="chook-picker-column"
      onTouchStart={onPointerDown}
      onTouchMove={onPointerMove}
      onTouchEnd={onPointerUp}
      onTouchCancel={onPointerUp}
      onMouseDown={onPointerDown}
      onMouseMove={onPointerMove}
      onMouseUp={onPointerUp}
    >
      <ul
        style={{
          overflowY: 'hidden',
          transform: `translate3d(0, ${offsetY}px, 0)`,
          transitionDuration: `${transitionDuration}ms`,
          transitionProperty: transitionDuration ? 'all' : 'none',
        }}
        onTransitionEnd={stopInertialSliding}
      >
        {column.map((option, index) => (
          <div
            key={option?.[fields.value]}
            tabIndex={0}
            role="button"
            aria-label="Select option"
            className="chook-picker-column-item"
            onClick={() => onClick(index)}
            onKeyDown={e => {
              if (e.key === 'Enter' || e.key === ' ') {
                onClick(index);
              }
            }}
          >
            <p
              className="chook-picker-column-label"
              style={{
                transform: `rotate3d(1, 0, 0, ${(index * OPTION_HEIGHT + offsetY) * OPTION_ROTATE_FACTOR}deg)`,
              }}
            >
              {option?.[fields.label]}
            </p>
          </div>
        ))}
      </ul>
    </div>
  );
});

Column.displayName = 'Column';
