// packages/picker/src/vue/components/Popup.vue
<script lang="ts" setup>
import { watch } from 'vue';

interface Props {
  teleport?: string | Element;
  modelValue: boolean;
}

interface Emits {
  'update:modelValue': [boolean];
  open: [];
  close: [];
  closed: [];
}

const props = withDefaults(defineProps<Props>(), {
  teleport: 'body',
});
const emits = defineEmits<Emits>();

watch(
  () => props.modelValue,
  value => {
    if (value) {
      document.body.style.overflow = 'hidden';
      emits('open');
    } else {
      document.body.style.overflow = '';
      emits('close');
    }
  },
  { immediate: true },
);
</script>

<template>
  <teleport :to="teleport">
    <transition name="chook-picker-fade">
      <div
        v-show="modelValue"
        class="chook-picker-mask"
        @click="$emit('update:modelValue', false)"
      ></div>
    </transition>

    <transition
      name="chook-picker-slide"
      @after-leave="$emit('closed')"
    >
      <div
        v-show="modelValue"
        class="chook-picker-container"
      >
        <slot></slot>
      </div>
    </transition>
  </teleport>
</template>

// packages/picker/src/react/components/Popup.tsx
import { useEffect, type PropsWithChildren } from 'react';
import { createPortal } from 'react-dom';
import { CSSTransition } from 'react-transition-group';

type Props = {
  teleport?: Element | DocumentFragment;
  show: boolean;
  onClose: () => void;
  onOpen?: () => void;
  onClosed?: () => void;
};

function Popup({ show, onClose, onOpen, onClosed, children, teleport = document.body }: PropsWithChildren<Props>) {
  useEffect(() => {
    if (show) {
      document.body.style.overflow = 'hidden';
      onOpen?.();
    } else {
      document.body.style.overflow = '';
    }
    return () => {
      document.body.style.overflow = '';
    };
  }, [show]);

  return createPortal(
    <>
      <CSSTransition
        in={show}
        timeout={300}
        classNames="chook-picker-fade"
        unmountOnExit
      >
        <div
          className="chook-picker-mask"
          onClick={onClose}
        />
      </CSSTransition>

      <CSSTransition
        in={show}
        timeout={300}
        classNames="chook-picker-slide"
        onExited={onClosed}
      >
        <div className="chook-picker-container">{children}</div>
      </CSSTransition>
    </>,
    teleport,
  );
}

export default Popup;
