// packages/picker/src/vue/components/TimePicker.vue
<script setup lang="ts">
import { computed, ref } from 'vue';
import { generateOptions, getValidTime, formatTime, getDefaultTime } from '../../shared/utils/common';
import { DEFAULT_TIME_TITLE, DEFAULT_TIME_COLUMNS } from '../../shared/constants';
import type { TimePickerColumnType, PickerSelectedValues, PickerFormatLabel } from '../../shared/types';
import Picker from './Picker.vue';

interface Props {
  show: boolean;
  modelValue?: PickerSelectedValues;
  title?: string;
  columnsType?: TimePickerColumnType[];
  minTime?: string;
  maxTime?: string;
  teleport?: string | Element;
  confirmButtonText?: string;
  cancelButtonText?: string;
  formatHourLabel?: PickerFormatLabel;
  formatMinuteLabel?: PickerFormatLabel;
  formatSecondLabel?: PickerFormatLabel;
}

interface Emits {
  'update:show': [boolean];
  'update:modelValue': [PickerSelectedValues];
  confirm: [PickerSelectedValues];
  cancel: [];
  open: [];
  closed: [];
}

const props = withDefaults(defineProps<Props>(), {
  title: DEFAULT_TIME_TITLE,
  columnsType: () => DEFAULT_TIME_COLUMNS,
  formatHourLabel: formatTime,
  formatMinuteLabel: formatTime,
  formatSecondLabel: formatTime,
});
const emits = defineEmits<Emits>();
const selectedValues = ref<PickerSelectedValues>([]);
const internalModelValue = ref<PickerSelectedValues>([]);

const isShowPicker = computed({
  get: () => props.show,
  set: value => emits('update:show', value),
});

const columns = computed(() => {
  const { columnsType } = props;
  const generateOptionsMap = {
    hour: generateHourOptions,
    minute: generateMinuteOptions,
    second: generateSecondOptions,
  };

  return columnsType.map(type => generateOptionsMap[type]());
});

const formattedMinTime = computed(() => {
  const minTime = getValidTime(props.minTime ?? '');

  return minTime ?? { hour: 0, minute: 0, second: 0 };
});

const formattedMaxTime = computed(() => {
  const maxTime = getValidTime(props.maxTime ?? '');

  return maxTime ?? { hour: 23, minute: 59, second: 59 };
});

function generateHourOptions() {
  const minHour = formattedMinTime.value.hour;
  const maxHour = formattedMaxTime.value.hour;

  return generateOptions(minHour, maxHour, props.formatHourLabel);
}

function generateMinuteOptions() {
  const selectedHour = getSelectedValue('hour');
  const { hour: minH, minute: minM } = formattedMinTime.value;
  const { hour: maxH, minute: maxM } = formattedMaxTime.value;
  const minMinute = selectedHour === minH ? minM : 0;
  const maxMinute = selectedHour === maxH ? maxM : 59;

  return generateOptions(minMinute, maxMinute, props.formatMinuteLabel);
}

function generateSecondOptions() {
  const selectedHour = getSelectedValue('hour');
  const selectedMinute = getSelectedValue('minute');
  const { hour: minH, minute: minM, second: minS } = formattedMinTime.value;
  const { hour: maxH, minute: maxM, second: maxS } = formattedMaxTime.value;
  const minSecond = selectedHour === minH && selectedMinute === minM ? minS : 0;
  const maxSecond = selectedHour === maxH && selectedMinute === maxM ? maxS : 59;

  return generateOptions(minSecond, maxSecond, props.formatSecondLabel);
}

function getSelectedValue(type: TimePickerColumnType) {
  const { columnsType } = props;
  const columnIndex = columnsType.indexOf(type);
  const value = selectedValues.value[columnIndex];

  if (value !== undefined) return Number(value);

  return getDefaultTime(formattedMinTime.value, formattedMaxTime.value, type);
}

function onConfirm(value: PickerSelectedValues) {
  emits('update:modelValue', value);
  internalModelValue.value = value;
  emits('confirm', value);
}

function onCancel() {
  emits('cancel');
}

function setDefaultValues() {
  emits('open');

  if (props.modelValue && props.modelValue.length) {
    selectedValues.value = [...props.modelValue];
    return;
  }
  const { columnsType } = props;

  selectedValues.value = columnsType.map(type => getSelectedValue(type));
}

function resetSelectedValues() {
  selectedValues.value = props.modelValue ? [...props.modelValue] : [...internalModelValue.value];
  emits('closed');
}
</script>

<template>
  <Picker
    v-model="selectedValues"
    v-model:show="isShowPicker"
    :title="title"
    :columns="columns"
    :teleport="teleport"
    :confirm-button-text="confirmButtonText"
    :cancel-button-text="cancelButtonText"
    linkage
    @confirm="onConfirm"
    @cancel="onCancel"
    @open="setDefaultValues"
    @closed="resetSelectedValues"
  />
</template>

// packages/picker/src/react/components/time-picker.tsx
import { useState, useMemo } from 'react';
import { generateOptions, getValidTime, formatTime, getDefaultTime } from '../../shared/utils/common';
import { DEFAULT_TIME_TITLE, DEFAULT_TIME_COLUMNS } from '../../shared/constants';
import type { TimePickerColumnType, PickerSelectedValues, PickerFormatLabel } from '../../shared/types';
import { Picker } from './picker';

interface Props {
  show: boolean;
  values?: PickerSelectedValues;
  title?: string;
  columnsType?: TimePickerColumnType[];
  minTime?: string;
  maxTime?: string;
  teleport?: Element | DocumentFragment;
  confirmButtonText?: string;
  cancelButtonText?: string;
  formatHourLabel?: PickerFormatLabel;
  formatMinuteLabel?: PickerFormatLabel;
  formatSecondLabel?: PickerFormatLabel;
  onConfirm?: (values: PickerSelectedValues) => void;
  onClose: () => void;
  onCancel?: () => void;
  onOpen?: () => void;
  onClosed?: () => void;
}

export function TimePicker({
  show,
  values,
  title = DEFAULT_TIME_TITLE,
  columnsType = DEFAULT_TIME_COLUMNS,
  minTime,
  maxTime,
  teleport,
  confirmButtonText,
  cancelButtonText,
  formatHourLabel = formatTime,
  formatMinuteLabel = formatTime,
  formatSecondLabel = formatTime,
  onConfirm,
  onClose,
  onCancel,
  onOpen,
  onClosed,
}: Props) {
  const [internalValues, setInternalValues] = useState<PickerSelectedValues>([]);
  const [selectedValues, setSelectedValues] = useState<PickerSelectedValues>([]);

  const formattedMinTime = useMemo(() => {
    return getValidTime(minTime ?? '') ?? { hour: 0, minute: 0, second: 0 };
  }, [minTime]);

  const formattedMaxTime = useMemo(() => {
    return getValidTime(maxTime ?? '') ?? { hour: 23, minute: 59, second: 59 };
  }, [maxTime]);

  const columns = useMemo(() => {
    const generateOptionsMap = {
      hour: generateHourOptions,
      minute: generateMinuteOptions,
      second: generateSecondOptions,
    };

    return columnsType.map(type => generateOptionsMap[type]());
  }, [
    columnsType,
    formattedMinTime,
    formattedMaxTime,
    selectedValues,
    formatHourLabel,
    formatMinuteLabel,
    formatSecondLabel,
  ]);

  function generateHourOptions() {
    return generateOptions(formattedMinTime.hour, formattedMaxTime.hour, formatHourLabel);
  }

  function generateMinuteOptions() {
    const selectedHour = getSelectedValue('hour');
    const { hour: minH, minute: minM } = formattedMinTime;
    const { hour: maxH, minute: maxM } = formattedMaxTime;
    const minMinute = selectedHour === minH ? minM : 0;
    const maxMinute = selectedHour === maxH ? maxM : 59;

    return generateOptions(minMinute, maxMinute, formatMinuteLabel);
  }

  function generateSecondOptions() {
    const selectedHour = getSelectedValue('hour');
    const selectedMinute = getSelectedValue('minute');
    const { hour: minH, minute: minM, second: minS } = formattedMinTime;
    const { hour: maxH, minute: maxM, second: maxS } = formattedMaxTime;
    const minSecond = selectedHour === minH && selectedMinute === minM ? minS : 0;
    const maxSecond = selectedHour === maxH && selectedMinute === maxM ? maxS : 59;

    return generateOptions(minSecond, maxSecond, formatSecondLabel);
  }

  function getSelectedValue(type: TimePickerColumnType) {
    const columnIndex = columnsType.indexOf(type);
    const value = selectedValues[columnIndex];

    if (value !== undefined) return Number(value);

    return getDefaultTime(formattedMinTime, formattedMaxTime, type);
  }

  function handleConfirm(confirmValues: PickerSelectedValues) {
    setInternalValues(confirmValues);
    onClose();
    onConfirm?.(confirmValues);
  }

  function handleCancel() {
    onClose();
    onCancel?.();
  }

  function setDefaultValues() {
    onOpen?.();

    if (values && values.length) {
      setSelectedValues([...values]);
    } else {
      setSelectedValues(columnsType.map(getSelectedValue));
    }
  }

  function handleClosed() {
    setSelectedValues(values ? [...values] : [...internalValues]);
    onClosed?.();
  }

  return (
    <Picker
      values={selectedValues}
      show={show}
      title={title}
      columns={columns}
      teleport={teleport}
      confirmButtonText={confirmButtonText}
      cancelButtonText={cancelButtonText}
      linkage
      onConfirm={handleConfirm}
      onClose={onClose}
      onChange={setSelectedValues}
      onCancel={handleCancel}
      onOpen={setDefaultValues}
      onClosed={handleClosed}
    />
  );
}
