// packages/create-app/template-react/src/pages/home/index.tsx
import { SvgIcon } from '@/components/common';
import { HelloWorld } from './components/hello-world';
import styles from './index.module.css';
import viteLogo from '/vite.svg';

export function Home() {
  return (
    <>
      <div>
        <a
          href="https://vite.dev"
          target="_blank"
          rel="noreferrer"
        >
          <img
            src={viteLogo}
            className={`${styles.logo} hover:filter-[drop-shadow(0_0_2em_#646cffaa)]`}
            alt="Vite logo"
          />
        </a>
        <a
          href="https://react.dev"
          target="_blank"
          rel="noreferrer"
          aria-label="React link"
        >
          <SvgIcon
            name="react"
            className={`${styles.logo} motion-safe:animate-logo-spin hover:filter-[drop-shadow(0_0_2em_#61dafbaa)]`}
          />
        </a>
      </div>

      <HelloWorld title="Vite + React" />
    </>
  );
}

// packages/create-app/template-vue/src/pages/home/index.vue
<script setup lang="ts">
import { SvgIcon } from '@/components/common';
import HelloWorld from './components/HelloWorld.vue';
</script>

<template>
  <div>
    <a
      href="https://vitejs.dev"
      target="_blank"
    >
      <img
        src="/vite.svg"
        class="logo"
        alt="Vite logo"
      />
    </a>
    <a
      href="https://vuejs.org/"
      target="_blank"
      aria-label="Vue link"
    >
      <svg-icon
        name="vue"
        class="logo hover:drop-shadow-[0_0_2em_#42b883aa]"
      />
    </a>
  </div>

  <hello-world msg="Vite + Vue" />
</template>

<style lang="css" scoped>
.logo {
  width: 96px;
  height: 96px;
  margin: 0 auto;
  padding: 24px;
  will-change: filter;
  transition: filter 300ms;

  &:hover {
    filter: drop-shadow(0 0 2em #646cffaa);
  }
}
</style>
