// packages/pdf-canvas/src/react/components/pdf-canvas.tsx
import { forwardRef, useEffect, useImperativeHandle, useMemo, useRef, type Ref } from 'react';
import { DEFAULT_SELECTION_OPTIONS } from '../../shared/constants';
import { useFabric } from '../hooks/use-fabric';
import { useResize } from '../hooks/use-resize';
import type { ComponentProps } from '../../shared/types/common';
import type {
  DropOffset,
  FabricPointerEvent,
  FabricSelectionClearedEvent,
  FabricSelectionCreatedEvent,
} from '../../shared/types/fabric';
import type { ImageProps, TextProps, TOptions } from 'fabric';

export interface PdfCanvasHandle {
  reload: () => Promise<void>;
  addImage: (src: string, options?: TOptions<ImageProps>) => void;
  addText: (text: string, options?: TOptions<TextProps>) => void;
  clearActive: () => void;
  deleteCanvas: () => void;
  copyActiveFabric: () => Promise<void>;
  deleteActiveFabric: () => void;
  canvasRef: React.RefObject<HTMLCanvasElement | null>;
}

interface ComponentEmits {
  onLoaded?: () => void;
  onReload?: () => void;
  onPointerDown?: (event: FabricPointerEvent) => void;
  onPointerMove?: (event: FabricPointerEvent) => void;
  onPointerUp?: (event: FabricPointerEvent) => void;
  onSelectionCreated?: (event: FabricSelectionCreatedEvent) => void;
  onSelectionCleared?: (event: FabricSelectionClearedEvent) => void;
}

export const PdfCanvas = forwardRef<PdfCanvasHandle, ComponentProps & ComponentEmits>(PdfCanvasComponent);

function PdfCanvasComponent(
  {
    file,
    page = 1,
    canvasId = 'PDF-canvas',
    fileZoom = 1,
    fileScale = 1,
    canvasScale = 1,
    canvasClass = '',
    isDrop = false,
    password,
    dropTextOptions,
    dropImageOptions,
    closeSvgOptions,
    selectionOptions,
    manualReload,
    onLoaded,
    onReload,
    onPointerDown,
    onPointerMove,
    onPointerUp,
    onSelectionCreated,
    onSelectionCleared,
  }: ComponentProps & ComponentEmits,
  ref: Ref<PdfCanvasHandle>,
) {
  const canvasRef = useRef<HTMLCanvasElement | null>(null);
  const computedCanvasId = `${canvasId}-${page - 1}`;
  const containerScale = useMemo(() => fileZoom * canvasScale, [fileZoom, canvasScale]);

  const computedSelectionOptions = useMemo(() => {
    return { ...DEFAULT_SELECTION_OPTIONS, ...selectionOptions };
  }, [selectionOptions]);

  const {
    createCanvas,
    specifyPage,
    addFabric,
    addTextFabric,
    renderImage,
    clearActive,
    deleteCanvas,
    scaleFabric,
    setCloseSvgOptions,
    copyActiveFabric,
    deleteActiveFabric,
  } = useFabric({
    id: computedCanvasId,
    selectionOptions: computedSelectionOptions,
    pointerDown: onPointerDown,
    pointerMove: onPointerMove,
    pointerUp: onPointerUp,
    selectionCreated: onSelectionCreated,
    selectionCleared: onSelectionCleared,
  });

  useResize(handleReload);

  async function setPDF() {
    window.requestAnimationFrame(async () => {
      createCanvas();

      if (file.PDFBase64.startsWith('data:image') || file.canvas) {
        const { canvas } = file;
        const scaleDown = canvas ? 7 : 3;
        const url = canvas?.length ? canvas[page - 1] : file.PDFBase64;

        renderImage({ url, scale: fileScale / scaleDown });
        return;
      }

      await specifyPage({
        page,
        PDFBase64: file.PDFBase64,
        scale: fileScale,
        password,
      });

      onLoaded?.();
    });
  }

  function dropImage(event: React.DragEvent) {
    event.preventDefault();
    event.stopPropagation();
    if (!isDrop || !event.dataTransfer) return;
    const { dataTransfer, nativeEvent } = event;
    const { offsetX, offsetY } = nativeEvent;
    const text = dataTransfer.getData('text/plain');
    const imageSrc = dataTransfer.getData('text/uri-list');
    const customOffset = dataTransfer.getData('custom/offset');
    const offset = customOffset ? JSON.parse(customOffset) : null;
    const options = { top: offsetY, left: offsetX };
    const dropOffset = { x: offset?.offsetX ?? 0, y: offset?.offsetY ?? 0 };

    if (imageSrc) {
      addImage(imageSrc, options, dropOffset);
    } else if (text) {
      addText(text, options, dropOffset);
    }
  }

  function addImage(src: string, options?: TOptions<ImageProps>, offset?: DropOffset) {
    addFabric(src, { ...dropImageOptions, ...options }, offset);
  }

  function addText(text: string, options?: TOptions<TextProps>, offset?: DropOffset) {
    addTextFabric(text, { ...dropTextOptions, ...options }, offset);
  }

  function handleReload() {
    if (!manualReload) setPDF();

    onReload?.();
  }

  useImperativeHandle(ref, () => ({
    reload: setPDF,
    addImage,
    addText,
    clearActive,
    deleteCanvas,
    copyActiveFabric,
    deleteActiveFabric,
    canvasRef,
  }));

  useEffect(() => {
    handleReload();
  }, [fileScale, page, file, password]);

  useEffect(() => {
    scaleFabric(containerScale);
  }, [containerScale]);

  useEffect(() => {
    setCloseSvgOptions(closeSvgOptions);
  }, [closeSvgOptions]);

  useEffect(() => {
    return () => deleteCanvas();
  }, []);

  return (
    <div
      style={{ transform: `scale(${containerScale})` }}
      onDragOver={e => e.preventDefault()}
      onDragEnter={e => e.preventDefault()}
      onDrop={dropImage}
    >
      <canvas
        id={computedCanvasId}
        ref={canvasRef}
        className={canvasClass}
      ></canvas>
    </div>
  );
}

// packages/pdf-canvas/src/vue/components/pdf-canvas.vue
<script setup lang="ts">
import { ref, nextTick, watch, computed, onBeforeUnmount } from 'vue';
import type { ImageProps, TextProps, TOptions } from 'fabric';
import { useFabric } from '../hooks/use-fabric';
import { useResize } from '../hooks/use-resize';
import { DEFAULT_SELECTION_OPTIONS } from '../../shared/constants';
import type { ComponentProps } from '../../shared/types/common';
import type {
  DropOffset,
  FabricSelectionCreatedEvent,
  FabricSelectionClearedEvent,
  FabricPointerEvent,
} from '../../shared/types/fabric';

interface Emits {
  loaded: [];
  reload: [];
  pointerDown: [event: FabricPointerEvent];
  pointerMove: [event: FabricPointerEvent];
  pointerUp: [event: FabricPointerEvent];
  selectionCreated: [event: FabricSelectionCreatedEvent];
  selectionCleared: [event: FabricSelectionClearedEvent];
}

const props = withDefaults(defineProps<ComponentProps>(), {
  canvasId: 'PDF-canvas',
  canvasClass: '',
  canvasScale: 1,
  page: 1,
  fileZoom: 1,
  fileScale: 1,
  isDrop: false,
  onDestroy: onBeforeUnmount,
});

const emit = defineEmits<Emits>();
const { onDestroy } = props;
const canvasRef = ref<HTMLCanvasElement | null>(null);
const canvasId = `${props.canvasId}-${props.page - 1}`;

const containerScale = computed(() => props.fileZoom * props.canvasScale);
const selectionOptions = computed(() => ({ ...DEFAULT_SELECTION_OPTIONS, ...props.selectionOptions }));

const {
  createCanvas,
  specifyPage,
  addFabric,
  addTextFabric,
  renderImage,
  clearActive,
  deleteCanvas,
  scaleFabric,
  setCloseSvgOptions,
  copyActiveFabric,
  deleteActiveFabric,
} = useFabric({
  id: canvasId,
  selectionOptions,
  pointerDown: event => emit('pointerDown', event),
  pointerMove: event => emit('pointerMove', event),
  pointerUp: event => emit('pointerUp', event),
  selectionCreated: event => emit('selectionCreated', event),
  selectionCleared: event => emit('selectionCleared', event),
});

setPDF();
useResize(handleReload);

async function setPDF() {
  const { file, page, fileScale: scale } = props;

  window.requestAnimationFrame(async () => {
    await nextTick();
    createCanvas();

    if (file.PDFBase64.startsWith('data:image') || file.canvas) {
      const { canvas } = file;
      const scaleDown = canvas ? 7 : 3;
      const url = canvas?.length ? canvas[page - 1] : file.PDFBase64;

      renderImage({ url, scale: scale / scaleDown });
      emit('loaded');
      return;
    }

    await specifyPage({
      page,
      PDFBase64: file.PDFBase64,
      scale,
      password: props.password,
    });

    emit('loaded');
  });
}

function dropImage(event: DragEvent) {
  if (!props.isDrop || !event.dataTransfer) return;
  const { dataTransfer, offsetX, offsetY } = event;
  const text = dataTransfer.getData('text/plain');
  const imageSrc = dataTransfer.getData('text/uri-list');
  const customOffset = dataTransfer.getData('custom/offset');
  const offset = customOffset ? JSON.parse(customOffset) : null;
  const options = { top: offsetY, left: offsetX };
  const dropOffset = { x: offset?.offsetX ?? 0, y: offset?.offsetY ?? 0 };

  if (imageSrc) {
    addImage(imageSrc, options, dropOffset);
  } else if (text) {
    addText(text, options, dropOffset);
  }
}

function addImage(src: string, options?: TOptions<ImageProps>, offset?: DropOffset) {
  addFabric(src, { ...props.dropImageOptions, ...options }, offset);
}

function addText(text: string, options?: TOptions<TextProps>, offset?: DropOffset) {
  addTextFabric(text, { ...props.dropTextOptions, ...options }, offset);
}

function handleReload() {
  if (!props.manualReload) setPDF();

  emit('reload');
}

watch([() => props.fileScale, () => props.page, () => props.file, () => props.password], handleReload);
watch(containerScale, scale => scaleFabric(scale), { immediate: true });
watch(() => props.closeSvgOptions, setCloseSvgOptions, { immediate: true });
onDestroy(deleteCanvas);
defineExpose({
  reload: setPDF,
  addImage,
  addText,
  clearActive,
  deleteCanvas,
  copyActiveFabric,
  deleteActiveFabric,
  canvasRef,
});
</script>

<template>
  <div
    :style="{ transform: `scale(${containerScale})` }"
    @dragover.prevent
    @dragenter.prevent
    @drop.stop.prevent="dropImage"
  >
    <canvas
      :id="canvasId"
      ref="canvasRef"
      :class="canvasClass"
    ></canvas>
  </div>
</template>
