// packages/picker/src/react/components/picker.tsx
import { useState, useEffect, useRef, useMemo, type ReactNode } from 'react';
import {
  extendFields,
  formatColumnsToCascade,
  getColumnsType,
  resetChildrenSelected,
  getIndexByValue,
} from '../../shared/utils/common';
import type { PickerFields, PickerColumn, PickerSelectedValues } from '../../shared/types';
import { Popup } from './popup';
import { Column, type ColumnRef } from './picker-column';
import '../../shared/index.scss';
import '../transition.scss';

interface Props {
  show: boolean;
  values?: PickerSelectedValues;
  title?: string;
  columns: PickerColumn | PickerColumn[];
  linkage?: boolean;
  loading?: boolean;
  loadingSlot?: ReactNode;
  emptySlot?: ReactNode;
  teleport?: Element | DocumentFragment;
  confirmButtonText?: string;
  cancelButtonText?: string;
  columnsFieldNames?: PickerFields;
  onConfirm: (values: PickerSelectedValues) => void;
  onClose: () => void;
  onChange?: (values: PickerSelectedValues) => void;
  onCancel?: () => void;
  onOpen?: () => void;
  onClosed?: () => void;
}

export function Picker({
  show,
  values,
  title,
  columns,
  linkage = false,
  loading = false,
  loadingSlot,
  emptySlot,
  teleport,
  confirmButtonText = 'Confirm',
  cancelButtonText = 'Cancel',
  columnsFieldNames,
  onConfirm,
  onClose,
  onChange,
  onCancel,
  onOpen,
  onClosed,
}: Props) {
  const [internalValues, setInternalValues] = useState<PickerSelectedValues>([]);
  const [selectedValues, setSelectedValues] = useState<PickerSelectedValues>([]);
  const [selectedIndices, setSelectedIndices] = useState<number[]>([]);
  const columnsRef = useRef<(ColumnRef | null)[]>([]);
  const fields = extendFields(columnsFieldNames);
  const columnsType = getColumnsType(columns, fields);

  const currentColumns = useMemo(() => {
    if (columnsType === 'single') return [columns] as PickerColumn[];
    if (columnsType === 'multiple') return columns as PickerColumn[];

    return formatColumnsToCascade(columns, selectedValues, fields);
  }, [columns, columnsType, selectedValues, fields]);

  useEffect(() => {
    onChange?.(selectedValues);

    if (!linkage) return;
    setInternalValues(selectedValues);
  }, [linkage, selectedValues]);

  useEffect(() => {
    const n = currentColumns.length;
    const newSelectedIndices = [];
    let isChange = false;

    for (let index = 0; index < n; index++) {
      const options = currentColumns[index];
      const value = selectedValues[index];
      const selectedIndex = getIndexByValue(options, value, fields);

      if (selectedIndex === -1) {
        const originIndex = selectedIndices[index] ?? 0;
        const specifyIndex = originIndex >= options.length ? options.length - 1 : 0;

        newSelectedIndices[index] = specifyIndex;
      } else {
        newSelectedIndices[index] = selectedIndex;
      }
      if (newSelectedIndices[index] !== selectedIndices[index]) {
        columnsRef.current[index]?.scrollToSelected(newSelectedIndices[index]);
        isChange = true;
      }
    }

    if (!isChange) return;
    setSelectedIndices(newSelectedIndices);
  }, [selectedValues, currentColumns, fields]);

  function updateSelectedValueByIndex(columnIndex: number, selectedIndex: number) {
    const options = currentColumns[columnIndex];
    const value = options[selectedIndex][fields.value];
    const oldValue = selectedValues[columnIndex];

    if (value === oldValue) return;
    const newSelectedValues = [...selectedValues];

    newSelectedValues[columnIndex] = value;

    if (columnsType === 'cascade') {
      const selectedOptions = options[selectedIndex];

      setSelectedValues(resetChildrenSelected(selectedOptions, columnIndex, newSelectedValues, fields));
    } else {
      setSelectedValues(newSelectedValues);
    }
  }

  function handleConfirm() {
    setInternalValues(selectedValues);
    onClose();
    onConfirm(selectedValues);
  }

  function handleCancel() {
    onClose();
    onCancel?.();
  }

  function handleOpen() {
    onOpen?.();
    setSelectedValues(values ? [...values] : [...internalValues]);
  }

  return (
    <Popup
      show={show}
      teleport={teleport}
      onOpen={handleOpen}
      onClose={onClose}
      onClosed={onClosed}
    >
      <div className="chook-picker-header">
        <button
          className="chook-picker-cancel"
          onClick={handleCancel}
        >
          {cancelButtonText}
        </button>
        <p className="chook-picker-title">{title}</p>
        <button
          className="chook-picker-confirm"
          onClick={handleConfirm}
        >
          {confirmButtonText}
        </button>
      </div>
      <div
        className="chook-picker-columns chook-picker-columns-backdrop"
        onTouchMove={e => e.stopPropagation()}
      >
        {!loading && !columns.length ? emptySlot : null}

        {currentColumns.map((column, index) => (
          <Column
            key={index}
            ref={el => (columnsRef.current[index] = el)}
            column={column}
            fields={fields}
            selectedIndex={selectedIndices[index]}
            onChange={selectedIndex => updateSelectedValueByIndex(index, selectedIndex)}
          />
        ))}

        <div className="chook-picker-mask-backdrop"></div>
      </div>

      {loading ? <div className="chook-picker-loading">{loadingSlot}</div> : null}
    </Popup>
  );
}

// packages/picker/src/vue/components/Picker.vue
<script setup lang="ts">
import { computed, nextTick, ref, watchEffect } from 'vue';
import {
  extendFields,
  formatColumnsToCascade,
  getColumnsType,
  resetChildrenSelected,
  getIndexByValue,
} from '../../shared/utils/common';
import type { PickerFields, PickerColumn, PickerSelectedValues } from '../../shared/types';
import Popup from './Popup.vue';
import Column from './PickerColumn.vue';
import '../../shared/index.scss';
import '../transition.scss';

interface Props {
  show: boolean;
  modelValue?: PickerSelectedValues;
  title?: string;
  columns: PickerColumn | PickerColumn[];
  linkage?: boolean;
  loading?: boolean;
  teleport?: string | Element;
  confirmButtonText?: string;
  cancelButtonText?: string;
  columnsFieldNames?: PickerFields;
}

interface Emits {
  'update:show': [boolean];
  'update:modelValue': [PickerSelectedValues];
  confirm: [PickerSelectedValues];
  cancel: [];
  open: [];
  closed: [];
}

const props = withDefaults(defineProps<Props>(), {
  confirmButtonText: 'Confirm',
  cancelButtonText: 'Cancel',
});
const emits = defineEmits<Emits>();
const internalModelValue = ref<PickerSelectedValues>([]);
const selectedValues = ref<PickerSelectedValues>([]);
const selectedIndices = ref<number[]>([]);
const columnsRef = ref<InstanceType<typeof Column>[] | null>(null);

const isShowPicker = computed({
  get: () => props.show,
  set: value => emits('update:show', value),
});

const fields = computed(() => extendFields(props.columnsFieldNames));

const columnsType = computed(() => getColumnsType(props.columns, fields.value));

const currentColumns = computed(() => {
  const { columns } = props;

  if (columnsType.value === 'single') return [columns] as PickerColumn[];
  if (columnsType.value === 'multiple') return columns as PickerColumn[];
  return formatColumnsToCascade(columns, selectedValues.value, fields.value);
});

function updateSelectedValueByIndex(columnIndex: number, selectedIndex: number) {
  const options = currentColumns.value[columnIndex];
  const value = options[selectedIndex][fields.value.value];
  const oldValue = selectedValues.value[columnIndex];

  if (value === oldValue) return;
  const newSelectedValues = [...selectedValues.value];

  newSelectedValues[columnIndex] = value;

  if (columnsType.value === 'cascade') {
    const selectedOptions = options[selectedIndex];

    selectedValues.value = resetChildrenSelected(selectedOptions, columnIndex, newSelectedValues, fields.value);
  } else {
    selectedValues.value = newSelectedValues;
  }

  if (!props.linkage) return;
  updateModelValue();
}

function updateModelValue() {
  emits('update:modelValue', selectedValues.value);
  internalModelValue.value = selectedValues.value;
}

function closePicker() {
  emits('update:show', false);
}

async function onOpen() {
  emits('open');
  await nextTick();
  selectedValues.value = props.modelValue ? [...props.modelValue] : [...internalModelValue.value];

  if (!columnsRef.value) return;
  await nextTick();
  columnsRef.value.forEach(column => column.scrollToSelected());
}

function onConfirm() {
  if (!props.linkage) {
    updateModelValue();
  }
  closePicker();
  emits('confirm', selectedValues.value);
}

function onCancel() {
  closePicker();
  emits('cancel');
}

watchEffect(() => {
  const n = currentColumns.value.length;
  const newSelectedIndices = [];

  for (let index = 0; index < n; index++) {
    const options = currentColumns.value[index];
    const value = selectedValues.value[index];
    const selectedIndex = getIndexByValue(options, value, fields.value);

    if (selectedIndex === -1) {
      const originIndex = selectedIndices.value[index] ?? 0;
      const specifyIndex = originIndex >= options.length ? options.length - 1 : 0;

      selectedValues.value[index] = options[specifyIndex][fields.value.value];
      newSelectedIndices[index] = specifyIndex;
    } else {
      newSelectedIndices[index] = selectedIndex;
    }

    if (newSelectedIndices[index] !== selectedIndices.value[index]) {
      columnsRef.value?.[index].scrollToSelected(newSelectedIndices[index]);
    }
  }
  selectedIndices.value = newSelectedIndices;
});
</script>

<template>
  <popup
    v-model="isShowPicker"
    :teleport="teleport"
    @open="onOpen"
    @closed="$emit('closed')"
  >
    <div class="chook-picker-header">
      <button
        class="chook-picker-cancel"
        @click="onCancel"
      >
        {{ cancelButtonText }}
      </button>
      <p class="chook-picker-title">{{ title }}</p>
      <button
        class="chook-picker-confirm"
        @click="onConfirm"
      >
        {{ confirmButtonText }}
      </button>
    </div>

    <div
      class="chook-picker-columns chook-picker-columns-backdrop"
      @touchmove.stop
    >
      <slot
        v-if="!loading && !columns.length"
        name="empty"
      ></slot>

      <template v-else>
        <Column
          v-for="(column, index) in currentColumns"
          :key="index"
          ref="columnsRef"
          :column="column"
          :fields="fields"
          :selected-index="selectedIndices[index]"
          @change="(selectedIndex: number) => updateSelectedValueByIndex(index, selectedIndex)"
        />

        <div class="chook-picker-mask-backdrop"></div>
      </template>
    </div>

    <div
      v-if="loading"
      class="chook-picker-loading"
    >
      <slot name="loading"></slot>
    </div>
  </popup>
</template>
