// packages/picker/src/react/components/popup.tsx
import { useEffect, useRef, type PropsWithChildren } from 'react';
import { createPortal } from 'react-dom';
import { CSSTransition } from 'react-transition-group';

type Props = {
  teleport?: Element | DocumentFragment;
  show: boolean;
  onClose: () => void;
  onOpen?: () => void;
  onClosed?: () => void;
};

export function Popup({
  show,
  onClose,
  onOpen,
  onClosed,
  children,
  teleport = document.body,
}: PropsWithChildren<Props>) {
  const containerRef = useRef<HTMLDivElement | null>(null);
  const maskRef = useRef<HTMLDivElement | null>(null);

  useEffect(() => {
    if (show) {
      document.body.style.overflow = 'hidden';
      onOpen?.();
    } else {
      document.body.style.overflow = '';
    }
    return () => {
      document.body.style.overflow = '';
    };
  }, [show]);

  function setContainerDisplay(value: string) {
    if (!containerRef.current) return;

    containerRef.current.style.setProperty('display', value);

    if (value === 'none') onClosed?.();
  }

  return createPortal(
    <>
      <CSSTransition
        in={show}
        timeout={300}
        nodeRef={maskRef}
        classNames="chook-picker-fade"
        unmountOnExit
      >
        <div
          ref={maskRef}
          role="presentation"
          className="chook-picker-mask"
          onClick={onClose}
          onKeyDown={event => {
            if (event.key === 'Escape') {
              onClose();
            }
          }}
        />
      </CSSTransition>

      <CSSTransition
        in={show}
        timeout={300}
        nodeRef={containerRef}
        classNames="chook-picker-slide"
        onEnter={() => setContainerDisplay('')}
        onExited={() => setContainerDisplay('none')}
      >
        <div
          ref={containerRef}
          className="chook-picker-container"
          style={{ display: 'none' }}
        >
          {children}
        </div>
      </CSSTransition>
    </>,
    teleport,
  );
}

// packages/picker/src/vue/components/Popup.vue
<script lang="ts" setup>
import { watch } from 'vue';

interface Props {
  teleport?: string | Element;
  modelValue: boolean;
}

interface Emits {
  'update:modelValue': [boolean];
  open: [];
  close: [];
  closed: [];
}

const props = withDefaults(defineProps<Props>(), {
  teleport: 'body',
});
const emits = defineEmits<Emits>();

watch(
  () => props.modelValue,
  value => {
    if (value) {
      document.body.style.overflow = 'hidden';
      emits('open');
    } else {
      document.body.style.overflow = '';
      emits('close');
    }
  },
  { immediate: true },
);
</script>

<template>
  <teleport :to="teleport">
    <transition name="chook-picker-fade">
      <div
        v-show="modelValue"
        class="chook-picker-mask"
        @click="$emit('update:modelValue', false)"
      ></div>
    </transition>

    <transition
      name="chook-picker-slide"
      @after-leave="$emit('closed')"
    >
      <div
        v-show="modelValue"
        class="chook-picker-container"
      >
        <slot></slot>
      </div>
    </transition>
  </teleport>
</template>
