// playground/react/src/pages/date-picker/components/label-formatter.tsx
import { DatePicker, type DatePickerColumnType } from '@component-hook/picker/react';
import { useState } from 'react';

const columnsType: DatePickerColumnType[] = ['month', 'day', 'year'];

export function LabelFormatterPicker() {
  const [pickerValues, setPickerValues] = useState<number[]>([]);

  return (
    <div style={{ maxWidth: '500px' }}>
      <DatePicker
        values={pickerValues}
        columnsType={columnsType}
        formatMonthLabel={formatMonthLabel}
        formatDayLabel={formatDayLabel}
        onChange={setPickerValues}
      />

      <p>Selected date: {pickerValues.join(' / ') || 'not selected yet'}</p>
    </div>
  );
}

function formatMonthLabel(month: string) {
  const MONTHS_MAP: Record<string, string> = {
    1: 'Jan',
    2: 'Feb',
    3: 'Mar',
    4: 'Apr',
    5: 'May',
    6: 'Jun',
    7: 'Jul',
    8: 'Aug',
    9: 'Sep',
    10: 'Oct',
    11: 'Nov',
    12: 'Dec',
  };

  return MONTHS_MAP[month];
}

function formatDayLabel(day: string) {
  return day.padStart(2, '0');
}

// docs/src/examples/date-picker/LabelFormatter.vue
<script setup lang="ts">
import { DatePicker } from '@component-hook/picker/vue';
import { ref } from 'vue';

const currentDate = ref<number[]>([]);

const MONTHS_MAP: Record<string, string> = {
  1: 'Jan',
  2: 'Feb',
  3: 'Mar',
  4: 'Apr',
  5: 'May',
  6: 'Jun',
  7: 'Jul',
  8: 'Aug',
  9: 'Sep',
  10: 'Oct',
  11: 'Nov',
  12: 'Dec',
};
</script>

<template>
  <date-picker
    v-model="currentDate"
    class="max-w-[500px] rounded-lg"
    :columns-type="['month', 'day', 'year']"
    :format-month-label="month => MONTHS_MAP[month]"
    :format-day-label="day => day.padStart(2, '0')"
  />

  <p class="mt-6 text-sm font-mono">Selected date: {{ currentDate.join(' / ') || 'not selected yet' }}</p>
</template>
