// playground/react/src/pages/picker/components/multi-column.tsx
import { Picker } from '@component-hook/picker/react';
import { useState } from 'react';

const columns = Array.from({ length: 2 }, () =>
  Array.from({ length: 50 }, (_, index) => ({ label: index, value: index })),
);

export function MultiColumnPicker() {
  const [pickerValues, setPickerValues] = useState<number[]>([2, 20]);

  return (
    <div style={{ maxWidth: '400px' }}>
      <Picker
        columns={columns}
        values={pickerValues}
        onChange={setPickerValues}
      />

      <p>Selected value: {pickerValues.join(' / ') || 'not selected yet'}</p>
    </div>
  );
}

// docs/src/examples/picker/MultiColumn.vue
<script setup lang="ts">
import { Picker } from '@component-hook/picker/vue';
import { ref } from 'vue';

const pickerValues = ref<number[]>([2, 20]);
const columns = Array.from({ length: 2 }, () =>
  Array.from({ length: 50 }, (_, index) => ({ label: index, value: index })),
);
</script>

<template>
  <picker
    v-model="pickerValues"
    :columns="columns"
    class="max-w-100 rounded-lg"
  />

  <p class="mt-6 font-mono text-sm">Selected value: {{ pickerValues.join(' / ') || 'not selected yet' }}</p>
</template>
